accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('<int:pk>/follow/', views.follow, name='follow'),
    path('password/', views.password, name='password'),
]

instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views as accounts_views
from posts import views as posts_views

urlpatterns = [
    path('', posts_views.index, name="root"),
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('<str:username>/', accounts_views.people, name="people"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/like/', views.like, name='like'),
    path('<int:pk>/comment/create', views.comment_create, name='comment_create'),
    path('comment/<int:pk>/delete', views.comment_delete, name='comment_delete'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, upload_to='profile/%Y%m%d')
    description = models.TextField(blank=True)
    nickname = models.CharField(max_length=40, blank=True)

class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followings")

posts/models.py
from django.db import models
from django.conf import settings


class Post(models.Model):
    content = models.CharField(max_length=150)
    image = models.ImageField(blank=True, upload_to='postings/%Y%m%d')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts", blank=True)
    def __str__(self):
        return self.content


class Comment(models.Model):
    content = models.CharField(max_length=150)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    def __str__(self):
        return self.content

accounts/forms.py
from .models import Profile
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name', )


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('image', 'nickname', 'description', )

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from .forms import CustomUserChangeForm, CustomUserCreationForm, ProfileForm
from .models import Profile


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            messages.success(request, 'Login success, welcome {}'.format(user.username))
            return redirect(request.GET.get('next') or 'posts:index')
        else:
            messages.success(request, 'Login fail, check your username or password')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/form.html', {'form':form})
    
    
def logout(request):
    auth_logout(request)
    messages.success(request, 'Logout success')
    return redirect('accounts:login')


def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user)
            auth_login(request, user)
            messages.success(request, 'Register Success, welcome {}'.format(user.username))
            return redirect('posts:index')
        else:
            messages.success(request, 'Login fail, check your username or password')
    else:
        form = CustomUserCreationForm()
    return render(request, 'accounts/form.html', {'form':form})
    

def people(request, username):
    people = get_object_or_404(get_user_model(), username=username)
    return render(request, 'accounts/people.html', {'people':people})


@login_required
def follow(request, pk):
    people = get_object_or_404(get_user_model(), pk=pk)
    if people in request.user.followers.all():
        request.user.followers.remove(people)
    elif people != request.user:
        request.user.followers.add(people)
    return redirect('people', people.username)
    

@login_required
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        user, created = Profile.objects.get_or_create(user=request.user)
        form2 = ProfileForm(request.POST, request.FILES, instance=user)
        print(request.FILES)
        if form.is_valid() and form2.is_valid():
            form.save()
            form2.save()
            messages.success(request, 'Update Success')
            return redirect('people', request.user.username)
        else:
            messages.success(request, 'Check your input')
    else:
        form = CustomUserChangeForm(instance=request.user)
        user, created = Profile.objects.get_or_create(user=request.user)
        form2 = ProfileForm(instance=user)
    return render(request, 'accounts/form2.html', {'form':form, 'form2':form2})
    

def password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('people', request.user.username)
    form = PasswordChangeForm(user=request.user)
    return render(request, 'accounts/form.html', {'form':form})

accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
<form method="post" class="col-md-6 offset-md-3">
  {% csrf_token %}
  {% bootstrap_form form %}
  <button type="submit" class="btn btn-outline-secondary">Submit</button>
</form>
{% endblock %}

accounts/templates/accounts/form2.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
<form method="post" class="col-md-6 offset-md-3" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% bootstrap_form form2 %}
  <button type="submit" class="btn btn-outline-secondary">Submit</button>
</form>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
<form method="post" class="col-md-6 offset-md-3">
  {% csrf_token %}
  {% bootstrap_form form %}
  <button type="submit" class="btn btn-outline-secondary">Submit</button>
</form>
{% endblock %}

accounts/templates/accounts/people.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="col-lg-10 offset-lg-1">
  <div class="row my-4 pb-5">
    <div class="col-4">
      <div class="col-8 offset-2">
        <img src="{% if people.profile.image %}{{ people.profile.image.url }}{% else %}{% get_media_prefix %}profile/default.jpg{% endif %}" class="img-fluid rounded-circle"></img>
      </div>
    </div>
    <div class="col-8">
      <div style="font-size: 28px;line-height: 32px;" class="mb-4">{{ people.username }}
      {% if request.user == people %}<a class="btn btn-outline-secondary ml-2 py-1 px-2" href="{% url 'accounts:update' %}">프로필수정</a>
      {% else %}
      {% if people in request.user.followers.all %}
      <a class="btn btn-outline-secondary ml-2 py-1 px-2" href="{% url 'accounts:follow' people.id %}">팔로잉</a>
      {% else %}
      <a class="btn btn-primary ml-2 py-1 px-2" href="{% url 'accounts:follow' people.id %}">팔로우</a>
      {% endif %}
      {% endif %}
      </div>
      <div class='mb-3'>게시물 <strong class="mr-2">{{ people.post_set.count }}</strong> 팔로워 <strong class="mr-2">{{ people.followings.count }}</strong> 팔로우 <strong class="mr-2">{{ people.followers.count }}</strong></div>
      <div class="mb-2"><strong>{{ people.last_name }}{{ people.first_name }}</strong></div>
      {% if people.profile %}
      <div class='mb-2'>
        {{ people.profile.description|linebreaks }}
      </div>
      {% endif %}
    </div>
  </div>
  <div class="row">
    {% for post in people.post_set.all %}
      {% if post.image %}
      <div class="col-4">
        <img src="{{ post.image.url }}" class="img-fluid"></img>
      </div>
      {% endif %}
    {% endfor %}
  </div>
</div>
{% endblock %}