instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views as accounts_views
from posts import views as posts_views

urlpatterns = [
    path('', posts_views.index, name="root"),
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('<str:username>/', accounts_views.people, name="people"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/like/', views.like, name='like'),
    path('<int:pk>/comment/create', views.comment_create, name='comment_create'),
    path('comment/<int:pk>/delete', views.comment_delete, name='comment_delete'),
]

posts/models.py
from django.db import models
from django.conf import settings


class Post(models.Model):
    content = models.CharField(max_length=150)
    image = models.ImageField(blank=True, upload_to='postings/%Y%m%d')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_posts", blank=True)
    def __str__(self):
        return self.content


class Comment(models.Model):
    content = models.CharField(max_length=150)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    def __str__(self):
        return self.content

posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    content = forms.CharField(label="content", widget=forms.Textarea(attrs={
                    'rows': 7,
                    'placeholder': '오늘은 무엇을 하셨나요'
                }))
    image = forms.ImageField()
    class Meta:
        model = Post
        fields = ('content', 'image',)


class CommentForm(forms.ModelForm):
    content = forms.CharField(label="", widget=forms.TextInput(attrs={'placeholder': '댓글 입력'}))
    class Meta:
        model = Comment
        fields = ('content',)

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostForm, CommentForm
from .models import Post, Comment
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.db.models import Q


def create(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:index')
    else:
        form = PostForm()
    return render(request, 'posts/create.html', {'form':form})


def update(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user != post.user:
        return redirect('posts:index')
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts:index')
    else:
        form = PostForm(instance=post)
    return render(request, 'posts/create.html', {'form':form})


@require_POST
def delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user != post.user:
        return redirect('posts:index')
    post.delete()
    return redirect('posts:index')


@login_required
def index(request):
    posts = Post.objects.filter(Q(user__in=request.user.followers.all())|Q(user=request.user)).order_by('-id')
    form = CommentForm()
    return render(request, 'posts/index.html', {'posts':posts, 'form':form})


@login_required
def like(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user in post.like_users.all():
        post.like_users.remove(request.user)
    else:
        post.like_users.add(request.user)
    return redirect('posts:index')


@login_required
@require_POST
def comment_create(request, pk):
    post = get_object_or_404(Post, pk=pk)
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.post = post
        comment.save()
    return redirect('posts:index')


@login_required
@require_POST
def comment_delete(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    if request.user == comment.user:
        comment.delete()
    return redirect('posts:index')

posts/templates/posts/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form form %}
  <button type="submit" class="btn btn-outline-secondary"> {% if form.instance.id %} Update {% else %} Upload {% endif %}</button>
</form>
{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
<div class="row justify-content-center">
  {% for post in posts %}
  <div class="card my-4" style="width: 40rem;">
      <a href="{% url 'people' post.user.username %}" class="card-header text-muted">{{ post.user }}</a>
    {% if post.image %}
    <img src="{{ post.image.url }}" class="card-img-top" alt="...">
    {% else %}
    <img src="https://picsum.photos/30{{ forloop.counter0 }}/30{{ forloop.counter0 }}/?random" class="card-img-top" alt="...">
    {% endif %}
    <div class="card-body py-2">
      <p class="card-text">{{ post.content }}</p>
      {% if post.user == request.user %}
      <div class="row justify-content-end mr-1">
        <a href="{% url 'posts:update' post.id %}" class="btn btn-outline-success mr-1">Update</a>
        <form action="{% url 'posts:delete' post.id %}" method="POST">{% csrf_token %}
          <button type="submit" class="btn btn-outline-danger"> Delete </button>
        </form>
      </div>
      {% endif %}
      <a href="{% url 'posts:like' post.id %}">
        {% if request.user in post.like_users.all %}
        <i class="fas fa-heart"></i>
        {% else %}
        <i class="far fa-heart"></i>
        {% endif %}
      </a>
      {{ post.like_users.count }}명
    </div>
    <div class="card-body py-1">
      {% if request.user.is_authenticated %}
      <form method="POST" action="{% url 'posts:comment_create' post.id %}">
        {% csrf_token %}
        <div class="row">
          <div class="col-md-10 col-9 pr-1">
            {% bootstrap_form form %}
          </div>
          <div class="col-1 ml-3">
            <input type="submit" class="btn btn-outline-primary" value="게시"/>
          </div>
        </div>
      </form>
      {% endif %}
    {% if post.comment_set.all %}
      {% for comment in post.comment_set.all reversed %}
      <div class="row m-2">
        <div class="mr-2">
          <strong>{{ comment.user.username }}</strong>
        </div>
        <div>
          {{ comment.content }}
        </div>
        {% if request.user == comment.user %}
        <div class="ml-auto">
          <form action="{% url 'posts:comment_delete' comment.id %}" method="POST">{% csrf_token %}
            <button type="submit" class="btn p-0"><i class="fas fa-times"></i></button>
          </form>
        </div>
        {% endif %}
      </div>
      {% endfor %}
    {% endif %}
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}